version: '3'

services:
  database:
    image: mariadb:5.5
    volumes:
      - database:/var/lib/mysql
      - import-database:/docker-entrypoint-initdb.d
    restart: on-failure
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_TCP_PORT: "${DATABASE_PORT}"
    networks:
      - backend
      - debug
    # docker exec indieweb_database_1 "mysql -u ${MYSQL_USER} -p ${MYSQL_USER} < /sql/dougbeal_wp116.sql"
    
  webserver-wordpress:
    build: webserver-wordpress
    depends_on:
      - pgp
      - wordpress
    links:
      - wordpress    
    ports:
      - "8000:80"
    restart: always
    volumes:
      # wait for v3.2 to be more widespread
      # - type: volume
      #   source: public-key
      #   target: ${WEBSERVER_ROOT}/.well-known/public-key
      #   volume:
      #     nocopy: true
      #     read_only: true
      - public-key:${WEBSERVER_ROOT}/.well-known/public-key
      - wordpress:${WEBSERVER_ROOT}
      - wordpress-themes:${WEBSERVER_ROOT}/wp-content/themes
      - wordpress-plugins:${WEBSERVER_ROOT}/wp-content/plugins
    environment:
      NGINX_HOST: ${HOSTNAME}
      NGINX_PORT: 80
      WORDPRESS_HOST: "${WORDPRESS_HOST}"
    networks:
      - frontend
      - debug
      - backend

  pgp: # build pgp identity for login
    build: pgp-identity
    volumes:
      - public-key:/app/pgp-identity/public-key
    networks:
      - backend
      
  wordpress:
    depends_on:
      - database
    build: wordpress
    volumes:
      - wordpress:${WORDPRESS_PATH}
      - wordpress-themes:${WORDPRESS_PATH}/wp-content/themes
      - wordpress-plugins:${WORDPRESS_PATH}/wp-content/plugins
    links:
      - database
    environment:
      WORDPRESS_PATH: ${WEBSERVER_ROOT}/wordpress
      WORDPRESS_DB_HOST: "${DATABASE_HOST}:${DATABASE_PORT}"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - backend
      - debug
    command: "/wait-for ${DATABASE_HOST}:${DATABASE_PORT} -- php-fpm"

  webserver-quill:
    build: webserver-quill
    depends_on:
      - quill
    links:
      - quill
    ports:
      - "8001:80"
    restart: always
    volumes:
      # wait for v3.2 to be more widespread
      # - type: volume
      #   source: public-key
      #   target: ${WEBSERVER_ROOT}/.well-known/public-key
      #   volume:
      #     nocopy: true
      #     read_only: true
      - quill:${WEBSERVER_ROOT}
    environment:
      NGINX_HOST: ${HOSTNAME}
      NGINX_PORT: 80
    networks:
      - frontend
      - debug
      - backend
      
  quill:
    build: quill
    depends_on:
      - database
    volumes:
      - quill:/var/www/html/Quill
    networks:
      - backend
      - debug
    command: "/wait-for ${DATABASE_HOST}:${DATABASE_PORT} -- php-fpm"
    
  
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - backend
  #     - debug

  # indieauth:
  #   depends_on:
  #     - redis
  #   build: indieauth
  #   links:
  #     - redis
  #   environment:
  #     /indieweb/indieauth/redis/hostname: redis
  #     /indieweb/indieauth/redis/port: 6379
  #     /indieweb/indieauth/domain: indieauth
  #     /indieweb/indieauth/port: ${INDIEAUTH_PORT}
  #   networks:
  #     - backend
  #     - debug

  # ownyourgram:
  #   build: ownyourgram
  #   depends_on:
  #     - webserver
  #   volumes:
  #     - ownyougram:/app/ownyourgram.com
  #   networks:
  #     - backend
  #     - debug


volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/database
      o: bind    
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress
      o: bind
  quill:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/quill
      o: bind      
  wordpress-themes:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress-themes
      o: bind
  wordpress-plugins:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress-plugins
      o: bind      
  import-wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-wordpress
      o: bind
  import-database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-database
      o: bind
  public-key:
  quill:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/quill
      o: bind    
  sempress:      
  sempress-child:
  nginx-config:
  sql:
  ownyougram:

networks:
  frontend:
    driver: bridge
  debug:
    driver: bridge
  backend:
    internal: true
