version: '2'

services:
  db:
    image: mariadb:5.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
       
  webserver:
    depends_on:
      - db     
    image: nginx:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress     

  # 4.7-branch:4.7.5
  wordpress:
    depends_on:
      - webserver
    image: wordpress:latest
    volumes:
      - ./data:/data
      - ./wp-content:/app/wp-content/themes/the-theme

  indieauth:
    build: indieauth
    ports:
      - "8000:80"    

  ownyourgram:
    build: ownyourgram
    depends_on:
      - webserver

volumes:
    db_data:
