version: '3'

services:
  database:
    image: mariadb:5.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_TCP_PORT: ${DATABASE_PORT}

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    restart: always
    links:
      - wordpress
      - indieauth
    volumes:
      - public-key:/usr/share/nginx/html/.well-known/public-key
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro      
      #- ?:/etc/nginx/conf.d/wordpress.template
      #- ?:/etc/nginx/conf.d/indieauth.template
    environment:
      - NGINX_HOST ${HOSTNAME}
      - NGINX_PORT 80

  # 4.7-branch:4.7.5
  wordpress:
    depends_on:
      - database
    build: wordpress
    volumes:
      - wordpress:/app/wordpress
      - wp-themes:/app/wordpress/wp-content/themes/the-theme
      - ownyougram:/app/ownyourgram.com
    links:
      - database
    environment:
      WORDPRESS_DB_HOST: database:${DATABASE_PORT}
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress      

  redis:
    image: redis:alpine

  indieauth:
    depends_on:
      - redis
    build: indieauth
    links:
      - redis
    environment:
      REDIS_IP: redis
      REDIS_PORT: 6379
      HOSTNAME: indieauth
      PORT: ${INDIEAUTH_PORT}

  ownyourgram:
    build: ownyourgram
    depends_on:
      - webserver
    volumes:
      - ownyougram:/app/ownyourgram.com

  pgp:
    build: pgp-identity
    volumes:
      - public-key:/app/pgp-identity/public-key

volumes:
    db_data:
    ownyougram:
    wordpress:
    wp-themes:
    public-key:
    nginx-config:

networks:
  default:
    driver: bridge
